using ForSureLife.Models.Enums;
using ForSureLife.repo.Models.Enroll;
using ForSureLife.repo.Models.Quote;
using ForSureLife.repo.Models.Rate;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;
using Microsoft.Extensions.Logging.Debug;
using System;
using System.Collections.Generic;
using System.Text;

namespace ForSureLife.repo
{
    public class ForSureLifeDBContext : DbContext
    {
        public ForSureLifeDBContext()
        {

        }

        public ForSureLifeDBContext(DbContextOptions<ForSureLifeDBContext> options) : base(options)
        {
        }

        //Quote DB
        public DbSet<Application> Application { get; set; }
        public DbSet<ApplicationInfo> ApplicationInfo { get; set; }
        public DbSet<FamilyOrBeneficiary> FamilyOrBeneficiary { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<Drug> Drugs { get; set; }
        public DbSet<FamilyMember> FamilyMember { get; set; }
        public DbSet<HealthQuestion> HealthQuestion { get; set; }
        public DbSet<Lead> Lead { get; set; }
        public DbSet<PaymentInfo> PaymentInfo { get; set; }
        public DbSet<Pharmacy> Pharmacy { get; set; }
        public DbSet<Plan> Plan { get; set; }
        public DbSet<PlanBenefit> PlanBenefit { get; set; }
        public DbSet<PlanQuote> PlanQuote { get; set; }
        public DbSet<Quote> Quote { get; set; }

        public DbSet<LeadSale> LeadSale { get; set; }
        public DbSet<Designee> Designee { get; set; }

        //Carrier Data
        public DbSet<BankInfo> BankInfo { get; set; }
        public DbSet<BirthPlaces> BirthPlaces { get; set; }
        public DbSet<CarrierDrug> CarrierDrug { get; set; }
        public DbSet<CarrierPlan> CarrierPlan { get; set; }
        public DbSet<CarrierPlanBenefit> CarrierPlanBenefit { get; set; }
        public DbSet<CarrierPlanDetails> CarrierPlanDetails { get; set; }
        public DbSet<CarrierPlanRate> CarrierPlanRate { get; set; }


        //Enum 
        public DbSet<AAFinalExpense> AmAmFinalExpense { get; set; }
        public DbSet<AmAmApplicationAnswers> AmAmApplicationAnswers { get; set; }
        public DbSet<AmAmApplicationQuestions> AmAmApplicationQuestions { get; set; }
        public DbSet<AmState> AmState { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (optionsBuilder.IsConfigured == false)
            {
                optionsBuilder.UseSqlServer(@"Data Source=(localdb)\ProjectsV13;Initial Catalog=ForSureLife;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");

            }
        }

        //protected override void OnModelCreating(ModelBuilder modelBuilder)
        //{
        //modelBuilder.Entity<AmState>().HasData(
        //    new AmState { AmStateId = new Guid("ed16aae9-3cb2-a51b-90e0-82ec73738333"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.AL },
        //new AmState { AmStateId = new Guid("1d7e5762-7c92-9682-8267-e6b86c4e8282"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.AK },
        //new AmState { AmStateId = new Guid("1df968a1-0835-9373-a47a-4390d91e1091"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.AR },
        //new AmState { AmStateId = new Guid("5c24d582-0d75-8645-3618-68bb3c5f4c51"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.AZ },
        //new AmState { AmStateId = new Guid("595994f6-6794-741a-4937-9cbdd3d18c20"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.CO },
        //new AmState { AmStateId = new Guid("0492e911-660f-3062-2ef3-2f178a9a7c77"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.CT },
        //new AmState { AmStateId = new Guid("37bb0cdb-04e8-7d90-035a-caf2f83e589e"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.GA },
        //new AmState { AmStateId = new Guid("47c393f6-250b-a5d0-3d88-fb95d8148ca8"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.HI },
        //new AmState { AmStateId = new Guid("fc0bc2ff-2eef-4b97-9f8b-5ff3067d248a"), InsuranceCompany = InsuranceCompany.Occidental, State = States.IA },
        //new AmState { AmStateId = new Guid("fbcf9730-480e-780e-17b2-edcbd13f8362"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.ID },
        //new AmState { AmStateId = new Guid("beaf6384-4747-8152-0887-fe19fe7157b1"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.IL },
        //new AmState { AmStateId = new Guid("21de2f96-1774-9bef-934c-50a24aa4603d"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.IN },
        //new AmState { AmStateId = new Guid("0536004d-a384-a7a7-04af-f73781164fa3"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.KS },
        //new AmState { AmStateId = new Guid("c09f80e2-0733-8048-58e8-aeb887c313a2"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.KY },
        //new AmState { AmStateId = new Guid("811edfe2-97a4-624f-9b8c-eb312da41ab3"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.LA },
        //new AmState { AmStateId = new Guid("c5c6c08a-2cca-321c-0918-08e84097547b"), InsuranceCompany = InsuranceCompany.Occidental, State = States.MA },
        //new AmState { AmStateId = new Guid("8d2c3d92-9a80-4f56-115d-cec7f9d07ad4"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.MD },
        //new AmState { AmStateId = new Guid("9b376a45-1bc5-5961-6d11-4163679d674a"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.ME },
        //new AmState { AmStateId = new Guid("40f57aa9-74f8-a654-54ea-d7bb796b8f9e"), InsuranceCompany = InsuranceCompany.Occidental, State = States.MI },
        //new AmState { AmStateId = new Guid("906cb2cc-0d16-88fe-6b70-209075703618"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.MN },
        //new AmState { AmStateId = new Guid("855e3657-1e75-4f1c-58ec-0f4ee28184a0"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.MO },
        //new AmState { AmStateId = new Guid("3ad1b55c-0fab-3a58-7baa-310cf20b13d4"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.MS },
        //new AmState { AmStateId = new Guid("871d6482-4d46-0626-4bbd-18ebc7c89f84"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.NC },
        //new AmState { AmStateId = new Guid("871d6482-4d46-0626-4bbd-18ebc7c89f85"), InsuranceCompany = InsuranceCompany.Occidental, State = States.NJ },
        //new AmState { AmStateId = new Guid("d340f944-5543-0825-a6fe-ffb33feba2dc"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.NE },
        //new AmState { AmStateId = new Guid("414aec1d-2f1b-980a-7cef-dc2a74338013"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.NM },
        //new AmState { AmStateId = new Guid("6d6f453c-2ba5-3594-8ee8-dcb7545604e5"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.NV },
        //new AmState { AmStateId = new Guid("078cc111-a264-7212-16cc-fba56d360f18"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.OK },
        //new AmState { AmStateId = new Guid("61b43371-6b2e-a3a0-9d83-643e397877c2"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.OH },
        //new AmState { AmStateId = new Guid("ebaeeabc-638d-9b52-2277-d2aca774019a"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.OR },
        //new AmState { AmStateId = new Guid("146b0509-03cd-66ec-7a5c-5a14fdf910ca"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.PA },
        //new AmState { AmStateId = new Guid("7b3f30e6-2fc0-00af-5463-d2cdb5371792"), InsuranceCompany = InsuranceCompany.Occidental, State = States.RI },
        //new AmState { AmStateId = new Guid("28f77124-2487-111b-24bb-108da88f3f9a"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.SC },
        //new AmState { AmStateId = new Guid("05a30bf4-6a99-479c-1b5a-9f196a6ba45a"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.TN },
        //new AmState { AmStateId = new Guid("0e2b7914-0408-5d00-761b-100167f6552c"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.TX },
        //new AmState { AmStateId = new Guid("0eb8cf7c-1196-6e1f-1559-94e22813972a"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.UT },
        //new AmState { AmStateId = new Guid("5a6be76d-67e9-5a2f-2d98-6b4f50ec3990"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.VA },
        //new AmState { AmStateId = new Guid("1b7fb102-77b3-a1dd-574c-ac2c23bf5c7a"), InsuranceCompany = InsuranceCompany.Occidental, State = States.VT },
        //new AmState { AmStateId = new Guid("0be543f8-0209-9f39-753b-27eef29649f9"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.WA },
        //new AmState { AmStateId = new Guid("25412f3a-5715-04d5-42a4-917306029a7a"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.WI },
        //new AmState { AmStateId = new Guid("f6a82da3-38cd-4d96-5b51-45abf82f07bd"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.WV },
        //new AmState { AmStateId = new Guid("a207e798-6387-3fda-8e7f-d2559e4da433"), InsuranceCompany = InsuranceCompany.AmericanAmicable, State = States.WY }
        //);


        //modelBuilder.Entity<AmAmApplicationQuestions>().HasData(
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bd-881a-376a-711e-757e27ce3469"), QuestionName = AmAmApplicationQuestion.Question1, ApplicationSection = ApplicationSection.KnockOut },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4be-881a-376a-711e-757e27ce5369"), QuestionName = AmAmApplicationQuestion.Question3, ApplicationSection = ApplicationSection.KnockOut },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4ba-881a-376a-711e-757e27ce6369"), QuestionName = AmAmApplicationQuestion.Question4, ApplicationSection = ApplicationSection.Modified },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-891a-376a-711e-757e27ce7369"), QuestionName = AmAmApplicationQuestion.Question5, ApplicationSection = ApplicationSection.Modified },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-851a-376a-711e-757e27ce8369"), QuestionName = AmAmApplicationQuestion.Question2, ApplicationSection = ApplicationSection.KnockOut },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-831a-376a-711e-757e27ce9369"), QuestionName = AmAmApplicationQuestion.Question6, ApplicationSection = ApplicationSection.Modified },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-821a-376a-711e-757e27ce3169"), QuestionName = AmAmApplicationQuestion.Question7a, ApplicationSection = ApplicationSection.Modified },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-811a-376a-711e-757e27ce3269"), QuestionName = AmAmApplicationQuestion.Question7b, ApplicationSection = ApplicationSection.Modified },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-801a-376a-711e-757e27ce3369"), QuestionName = AmAmApplicationQuestion.Question7c, ApplicationSection = ApplicationSection.Modified },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-882a-376a-711e-757e27ce3469"), QuestionName = AmAmApplicationQuestion.Question7d, ApplicationSection = ApplicationSection.Modified },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-883a-376a-711e-757e27ce3569"), QuestionName = AmAmApplicationQuestion.Question8a, ApplicationSection = ApplicationSection.Graded },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-884a-376a-711e-757e27ce3669"), QuestionName = AmAmApplicationQuestion.Question8b, ApplicationSection = ApplicationSection.Graded },
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = new Guid("e494a4bc-885a-376a-711e-757e27ce3769"), QuestionName = AmAmApplicationQuestion.Question8c, ApplicationSection = ApplicationSection.Graded }
        //    );


        //modelBuilder.Entity<CarrierPlanRate>().HasData(
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 32.96m, Age = 50, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 34.9m, Age = 51, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 36.67m, Age = 52, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 39.14m, Age = 53, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 40.94m, Age = 54, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 42.49m, Age = 55, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 44.18m, Age = 56, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 45.32m, Age = 57, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 47.64m, Age = 58, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.5m, Age = 59, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 50.47m, Age = 60, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 53.38m, Age = 61, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 56.09m, Age = 62, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 58.71m, Age = 63, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 61.8m, Age = 64, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 64.89m, Age = 65, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 69.24m, Age = 66, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 73.78m, Age = 67, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 78.7m, Age = 68, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.12m, Age = 69, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 86.53m, Age = 70, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 92.03m, Age = 71, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 97.83m, Age = 72, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 104.4m, Age = 73, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 111.76m, Age = 74, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 119.74m, Age = 75, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 128.75m, Age = 76, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 138.02m, Age = 77, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 150.28m, Age = 78, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 161.92m, Age = 79, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 174.07m, Age = 80, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 187.87m, Age = 81, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 202.91m, Age = 82, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 217.02m, Age = 83, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 232.78m, Age = 84, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 248.49m, Age = 85, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },

        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 43.12m, Age = 50, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 45.03m, Age = 51, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 47.09m, Age = 52, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.42m, Age = 53, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 51.61m, Age = 54, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 53.82m, Age = 55, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 56.05m, Age = 56, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 58.29m, Age = 57, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 61.08m, Age = 58, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 63.35m, Age = 59, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 65.82m, Age = 60, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 70.04m, Age = 61, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 73.13m, Age = 62, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 76.01m, Age = 63, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 79.64m, Age = 64, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.43m, Age = 65, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 88.51m, Age = 66, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 93.22m, Age = 67, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 98.88m, Age = 68, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 104.55m, Age = 69, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 108.72m, Age = 70, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 115.15m, Age = 71, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 121.93m, Age = 72, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 129.6m, Age = 73, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 137.51m, Age = 74, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 147.55m, Age = 75, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 157.59m, Age = 76, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 168.1m, Age = 77, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 180.87m, Age = 78, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 191.58m, Age = 79, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 203.53m, Age = 80, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 216.3m, Age = 81, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 229.56m, Age = 82, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 246.08m, Age = 83, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 266.64m, Age = 84, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //         new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 289.69m, Age = 85, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //       new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 27.3m, Age = 50, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 29.36m, Age = 51, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 30.58m, Age = 52, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 32.21m, Age = 53, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 33.74m, Age = 54, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 35.28m, Age = 55, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 36.42m, Age = 56, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 37.7m, Age = 57, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 38.77m, Age = 58, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 40.17m, Age = 59, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 40.48m, Age = 60, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 42.85m, Age = 61, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 44.5m, Age = 62, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 46.44m, Age = 63, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 48.5m, Age = 64, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 50.47m, Age = 65, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 53.59m, Age = 66, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 56.34m, Age = 67, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 59.45m, Age = 68, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 62.52m, Age = 69, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 65.61m, Age = 70, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 69.53m, Age = 71, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 73.65m, Age = 72, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 78.84m, Age = 73, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.69m, Age = 74, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 89.87m, Age = 75, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 95.83m, Age = 76, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 101.29m, Age = 77, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 108.15m, Age = 78, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 116.6m, Age = 79, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 126.18m, Age = 80, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 135.75m, Age = 81, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 146.26m, Age = 82, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 158.11m, Age = 83, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 170.98m, Age = 84, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },
        //    new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 185.66m, Age = 85, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = false },

        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 32.55m, Age = 50, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 33.62m, Age = 51, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 35.34m, Age = 52, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 37.29m, Age = 53, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 38.73m, Age = 54, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 40.94m, Age = 55, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 42.23m, Age = 56, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 44.2m, Age = 57, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 45.91m, Age = 58, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 47.7m, Age = 59, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.01m, Age = 60, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 51.46m, Age = 61, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 54.08m, Age = 62, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 56.85m, Age = 63, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 59.78m, Age = 64, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 62.57m, Age = 65, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 65.88m, Age = 66, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 69.33m, Age = 67, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 72.1m, Age = 68, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 77.12m, Age = 69, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 79.02m, Age = 70, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.2m, Age = 71, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 87.61m, Age = 72, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 92.61m, Age = 73, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 97.75m, Age = 74, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 104.29m, Age = 75, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 112.49m, Age = 76, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 120m, Age = 77, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 127.85m, Age = 78, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 139.06m, Age = 79, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 150.62m, Age = 80, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 164.14m, Age = 81, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 179.51m, Age = 82, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 195.69m, Age = 83, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 214.76m, Age = 84, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 236.13m, Age = 85, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Immediate, Tobacoo = true },

        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 40.1m, Age = 50, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 42.35m, Age = 51, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 44.61m, Age = 52, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 47.16m, Age = 53, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.72m, Age = 54, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 52.27m, Age = 55, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 54.51m, Age = 56, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 56.86m, Age = 57, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 59.33m, Age = 58, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 61.91m, Age = 59, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 63.91m, Age = 60, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 67.32m, Age = 61, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 71.08m, Age = 62, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 74.96m, Age = 63, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 79.08m, Age = 64, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.43m, Age = 65, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 89.84m, Age = 66, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 96.82m, Age = 67, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 104.25m, Age = 68, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 112.25m, Age = 69, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 116.03m, Age = 70, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 123.89m, Age = 71, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 133.9m, Age = 72, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 144.2m, Age = 73, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 155.02m, Age = 74, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 166.09m, Age = 75, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 179.53m, Age = 76, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 196.73m, Age = 77, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 215.27m, Age = 78, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 234.33m, Age = 79, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 254.2m, Age = 80, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 269.86m, Age = 81, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 283.87m, Age = 82, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 296.64m, Age = 83, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 307.97m, Age = 84, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 312.35m, Age = 85, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },

        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 60.54m, Age = 50, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 63.59m, Age = 51, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 66.64m, Age = 52, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 70.09m, Age = 53, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 73.54m, Age = 54, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 76.99m, Age = 55, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 80.07m, Age = 56, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.32m, Age = 57, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 86.73m, Age = 58, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 90.3m, Age = 59, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 93.06m, Age = 60, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 97.77m, Age = 61, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 102.96m, Age = 62, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 108.31m, Age = 63, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 113.99m, Age = 64, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 120m, Age = 65, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 127.56m, Age = 66, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 135.81m, Age = 67, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 144.57m, Age = 68, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 154.02m, Age = 69, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 158.49m, Age = 70, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 167.77m, Age = 71, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 178.25m, Age = 72, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 190.28m, Age = 73, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 204.35m, Age = 74, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 217.59m, Age = 75, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 237.11m, Age = 76, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 255.76m, Age = 77, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 274.12m, Age = 78, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 295.71m, Age = 79, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 313.12m, Age = 80, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 316.15m, Age = 81, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 320.54m, Age = 82, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 325.48m, Age = 83, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 336.06m, Age = 84, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 359.73m, Age = 85, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },

        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 31.6m, Age = 50, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 33.24m, Age = 51, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 34.88m, Age = 52, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 36.73m, Age = 53, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 38.58m, Age = 54, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 40.43m, Age = 55, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 42.11m, Age = 56, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 43.88m, Age = 57, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 45.73m, Age = 58, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 47.68m, Age = 59, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.18m, Age = 60, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 51.75m, Age = 61, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 54.58m, Age = 62, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 57.49m, Age = 63, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 60.58m, Age = 64, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 63.86m, Age = 65, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 68.27m, Age = 66, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 73.08m, Age = 67, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 78.19m, Age = 68, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.7m, Age = 69, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 86.3m, Age = 70, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 91.71m, Age = 71, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 97.82m, Age = 72, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 104.83m, Age = 73, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 113.3m, Age = 74, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 120.77m, Age = 75, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 129.78m, Age = 76, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 140.6m, Age = 77, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 154.5m, Age = 78, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 167.38m, Age = 79, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 182.31m, Age = 80, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 197.76m, Age = 81, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 213.21m, Age = 82, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 227.63m, Age = 83, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 241.02m, Age = 84, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 248.49m, Age = 85, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 39.42m, Age = 50, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 41.7m, Age = 51, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 43.99m, Age = 52, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 46.58m, Age = 53, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.16m, Age = 54, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 51.76m, Age = 55, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 54.62m, Age = 56, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 57.63m, Age = 57, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 60.79m, Age = 58, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 64.11m, Age = 59, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 66.67m, Age = 60, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 71.04m, Age = 61, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 75.86m, Age = 62, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 80.83m, Age = 63, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 86.11m, Age = 64, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 91.67m, Age = 65, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 97.27m, Age = 66, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 103.39m, Age = 67, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 109.89m, Age = 68, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 115.36m, Age = 69, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 120.21m, Age = 70, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 127.72m, Age = 71, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 134.86m, Age = 72, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 143.78m, Age = 73, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 152.18m, Age = 74, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 164.03m, Age = 75, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 174.29m, Age = 76, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 180.79m, Age = 77, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 193.5m, Age = 78, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 207.22m, Age = 79, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 224.54m, Age = 80, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 238.85m, Age = 81, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 258.06m, Age = 82, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 278.28m, Age = 83, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 301.39m, Age = 84, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 328.83m, Age = 85, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Graded, Tobacoo = true },

        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 47.26m, Age = 50, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.51m, Age = 51, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 51.76m, Age = 52, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 54.3m, Age = 53, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 56.85m, Age = 54, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 59.1m, Age = 55, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 62.07m, Age = 56, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 65.21m, Age = 57, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 68.51m, Age = 58, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 71.96m, Age = 59, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 74.63m, Age = 60, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 79.19m, Age = 61, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 84.22m, Age = 62, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 89.4m, Age = 63, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 94.44m, Age = 64, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 99.75m, Age = 65, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 106.46m, Age = 66, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 113.79m, Age = 67, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 121.62m, Age = 68, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 129.48m, Age = 69, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 133.2m, Age = 70, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 141.58m, Age = 71, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 151.05m, Age = 72, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 161.15m, Age = 73, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 170.68m, Age = 74, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 183.24m, Age = 75, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 197.86m, Age = 76, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 215.62m, Age = 77, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 234.14m, Age = 78, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 253.37m, Age = 79, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 271.98m, Age = 80, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 287.61m, Age = 81, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 303.16m, Age = 82, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 319.58m, Age = 83, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 347.84m, Age = 84, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 381.41m, Age = 85, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 71.47m, Age = 50, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 75.83m, Age = 51, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 79.54m, Age = 52, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 83.74m, Age = 53, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 87.95m, Age = 54, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 90.87m, Age = 55, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 95.45m, Age = 56, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 99.83m, Age = 57, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 104.43m, Age = 58, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 109.25m, Age = 59, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 112.46m, Age = 60, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 118.79m, Age = 61, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 125.76m, Age = 62, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 132.96m, Age = 63, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 139.29m, Age = 64, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 146.59m, Age = 65, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 155.29m, Age = 66, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 165.56m, Age = 67, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 175.74m, Age = 68, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 185.9m, Age = 69, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 190.71m, Age = 70, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 201.14m, Age = 71, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 212.92m, Age = 72, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 225.91m, Age = 73, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 238.15m, Age = 74, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 255.41m, Age = 75, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 271.5m, Age = 76, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 280.96m, Age = 77, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 299.45m, Age = 78, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 319.42m, Age = 79, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 337.76m, Age = 80, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 362.12m, Age = 81, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 389.82m, Age = 82, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 415.13m, Age = 83, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 448.15m, Age = 84, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 487.35m, Age = 85, Gender = Gender.Male, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 38.07m, Age = 50, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 40.14m, Age = 51, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 42.21m, Age = 52, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 44.55m, Age = 53, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 46.89m, Age = 54, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.03m, Age = 55, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 51.49m, Age = 56, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 54.09m, Age = 57, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 56.83m, Age = 58, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 59.69m, Age = 59, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 61.89m, Age = 60, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 65.67m, Age = 61, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 69.82m, Age = 62, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 74.12m, Age = 63, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 78.29m, Age = 64, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 82.69m, Age = 65, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 88.61m, Age = 66, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 94.65m, Age = 67, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 100.62m, Age = 68, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 106.56m, Age = 69, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 109.08m, Age = 70, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 115.89m, Age = 71, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 123.58m, Age = 72, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 131.78m, Age = 73, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 139.52m, Age = 74, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 149.73m, Age = 75, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 160.46m, Age = 76, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 166.36m, Age = 77, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 177.92m, Age = 78, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 190.4m, Age = 79, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 203.79m, Age = 80, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 219.16m, Age = 81, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 234.41m, Age = 82, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 250.24m, Age = 83, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 270.85m, Age = 84, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 295.31m, Age = 85, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = false },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 44.57m, Age = 50, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 47.38m, Age = 51, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 49.99m, Age = 52, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 52.94m, Age = 53, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 55.9m, Age = 54, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 58.59m, Age = 55, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 62.21m, Age = 56, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 66.01m, Age = 57, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 69.69m, Age = 58, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 73.86m, Age = 59, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 77.08m, Age = 60, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 82.57m, Age = 61, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 88.62m, Age = 62, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 94.87m, Age = 63, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 101.03m, Age = 64, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 107.5m, Age = 65, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 115.05m, Age = 66, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 122.74m, Age = 67, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 130.3m, Age = 68, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 139.72m, Age = 69, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 143.89m, Age = 70, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 152.54m, Age = 71, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 162.31m, Age = 72, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 173.52m, Age = 73, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 184.95m, Age = 74, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 199.91m, Age = 75, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 219.34m, Age = 76, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 229.32m, Age = 77, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 248.83m, Age = 78, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 268.69m, Age = 79, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 287.23m, Age = 80, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 312.71m, Age = 81, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 341.67m, Age = 82, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 372.16m, Age = 83, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 406.99m, Age = 84, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true },
        //        new CarrierPlanRate { CarrierPlanRateId = Guid.NewGuid(), AnnualRate = 448.38m, Age = 85, Gender = Gender.Female, PremiumType = SeniorChoicePremiumType.Premium, Tobacoo = true }
        //    );


        //modelBuilder.Entity<AmAmApplicationQuestions>().HasData(
        //    new AmAmApplicationQuestions { AmAmApplicationQuestionsId = Guid.NewGuid(), ApplicationSection = ApplicationSection.HealthInformation, QuestionName ="", QuestionPosition = "" }
        //    ) ;

        //}
    }
}
