using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace ForSureLife.repo.Migrations
{
    public partial class AddingBirthPalaceAbbreviation : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Abbreviation",
                table: "BirthPlaces",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.Sql("Truncate table dbo.BirthPlaces");

            migrationBuilder.InsertData(
                                 table: "BirthPlaces",
                                 columns: new[] { "BirthPlacesId", "Name", "Abbreviation" },
                                 values: new object[,]
                                 {
                                     { Guid.NewGuid(), "Alabama","AL" },
                                     { Guid.NewGuid(), "Alaska","AK" },
                                     { Guid.NewGuid(), "Arizona","AZ" },
                                     { Guid.NewGuid(), "Arkansas","AR" },
                                     { Guid.NewGuid(), "California","CA" },
                                     { Guid.NewGuid(), "Colorado","CO" },
                                     { Guid.NewGuid(), "Connecticut","CT" },
                                     { Guid.NewGuid(), "Delaware","DE" },
                                     { Guid.NewGuid(), "Florida","FL" },
                                     { Guid.NewGuid(), "Georgia","GA" },
                                     { Guid.NewGuid(), "Hawaii","HI" },
                                     { Guid.NewGuid(), "Idaho","ID" },
                                     { Guid.NewGuid(), "Illinois","IL" },
                                     { Guid.NewGuid(), "Indiana","IN" },
                                     { Guid.NewGuid(), "Iowa","IA" },
                                     { Guid.NewGuid(), "Kansas","KS" },
                                     { Guid.NewGuid(), "Kentucky","KY" },
                                     { Guid.NewGuid(), "Louisiana","LA" },
                                     { Guid.NewGuid(), "Maine","ME" },
                                     { Guid.NewGuid(), "Maryland","MD" },
                                     { Guid.NewGuid(), "Massachusetts","MA" },
                                     { Guid.NewGuid(), "Michigan","MI" },
                                     { Guid.NewGuid(), "Minnesota","MN" },
                                     { Guid.NewGuid(), "Mississippi","MS" },
                                     { Guid.NewGuid(), "Missouri","MO" },
                                     { Guid.NewGuid(), "Montana","MT" },
                                     { Guid.NewGuid(), "Nebraska","NE" },
                                     { Guid.NewGuid(), "Nevada","NV" },
                                     { Guid.NewGuid(), "New Hampshire","NH" },
                                     { Guid.NewGuid(), "New Jersey","NJ" },
                                     { Guid.NewGuid(), "New Mexico","NM" },
                                     { Guid.NewGuid(), "New York","NY" },
                                     { Guid.NewGuid(), "North Carolina","NC" },
                                     { Guid.NewGuid(), "North Dakota","ND" },
                                     { Guid.NewGuid(), "Ohio","OH" },
                                     { Guid.NewGuid(), "Oklahoma","OK" },
                                     { Guid.NewGuid(), "Oregon","OR" },
                                     { Guid.NewGuid(), "Pennsylvania","PA" },
                                     { Guid.NewGuid(), "Rhode Island","RI" },
                                     { Guid.NewGuid(), "South Carolina","SC" },
                                     { Guid.NewGuid(), "South Dakota","SD" },
                                     { Guid.NewGuid(), "Tennessee","TN" },
                                     { Guid.NewGuid(), "Texas","TX" },
                                     { Guid.NewGuid(), "Utah","UT" },
                                     { Guid.NewGuid(), "Vermont","VT" },
                                     { Guid.NewGuid(), "Virginia","VA" },
                                     { Guid.NewGuid(), "Washington","WA" },
                                     { Guid.NewGuid(), "West Virginia","WV" },
                                     { Guid.NewGuid(), "Wisconsin","WI" },
                                     { Guid.NewGuid(), "Wyoming","WY" },
                                     { Guid.NewGuid(), "American Samoa","Americ" },
                                     { Guid.NewGuid(), "District of Columbia","DC" },
                                     { Guid.NewGuid(), "Federated States of Micronesia","Federa" },
                                     { Guid.NewGuid(), "Guam","Guam" },
                                     { Guid.NewGuid(), "Marshall Islands","Marsha" },
                                     { Guid.NewGuid(), "Northern Mariana Islands","Northe" },
                                     { Guid.NewGuid(), "Palau","Palau" },
                                     { Guid.NewGuid(), "Puerto Rico","Puerto" },
                                     { Guid.NewGuid(), "Virgin Islands","Virgin" },
                                     { Guid.NewGuid(), "Afghanistan","Afghan" },
                                     { Guid.NewGuid(), "Albania","Albani" },
                                     { Guid.NewGuid(), "Algeria","Algeri" },
                                     { Guid.NewGuid(), "Andorra","Andorr" },
                                     { Guid.NewGuid(), "Angola","Angola" },
                                     { Guid.NewGuid(), "Antigua and Barbuda","Antigu" },
                                     { Guid.NewGuid(), "Argentina","Argent" },
                                     { Guid.NewGuid(), "Armenia","Armeni" },
                                     { Guid.NewGuid(), "Australia","Austra" },
                                     { Guid.NewGuid(), "Austria","Austri" },
                                     { Guid.NewGuid(), "Azerbaijan","Azerba" },
                                     { Guid.NewGuid(), "Bahamas","Bahama" },
                                     { Guid.NewGuid(), "Bahrain","Bahrai" },
                                     { Guid.NewGuid(), "Bangladesh","Bangla" },
                                     { Guid.NewGuid(), "Barbados","Barbad" },
                                     { Guid.NewGuid(), "Belarus","Belaru" },
                                     { Guid.NewGuid(), "Belgium","Belgiu" },
                                     { Guid.NewGuid(), "Belize","Belize" },
                                     { Guid.NewGuid(), "Benin","Benin" },
                                     { Guid.NewGuid(), "Bhutan","Bhutan" },
                                     { Guid.NewGuid(), "Bolivia","Bolivi" },
                                     { Guid.NewGuid(), "Bosnia and Herzegovina","Bosnia" },
                                     { Guid.NewGuid(), "Botswana","Botswa" },
                                     { Guid.NewGuid(), "Brazil","Brazil" },
                                     { Guid.NewGuid(), "Brunei","Brunei" },
                                     { Guid.NewGuid(), "Bulgaria","Bulgar" },
                                     { Guid.NewGuid(), "Burkina Faso","Burkin" },
                                     { Guid.NewGuid(), "Burundi","Burund" },
                                     { Guid.NewGuid(), "Côte d'Ivoire","Côte d" },
                                     { Guid.NewGuid(), "Cabo Verde","Cabo V" },
                                     { Guid.NewGuid(), "Cambodia","Cambod" },
                                     { Guid.NewGuid(), "Cameroon","Camero" },
                                     { Guid.NewGuid(), "Canada","Canada" },
                                     { Guid.NewGuid(), "Central African Republic","Centra" },
                                     { Guid.NewGuid(), "Chad","Chad" },
                                     { Guid.NewGuid(), "Chile","Chile" },
                                     { Guid.NewGuid(), "China","China" },
                                     { Guid.NewGuid(), "Colombia","Colomb" },
                                     { Guid.NewGuid(), "Comoros","Comoro" },
                                     { Guid.NewGuid(), "Congo (Congo-Brazzaville)","Congo " },
                                     { Guid.NewGuid(), "Costa Rica","Costa " },
                                     { Guid.NewGuid(), "Croatia","Croati" },
                                     { Guid.NewGuid(), "Cuba","Cuba" },
                                     { Guid.NewGuid(), "Cyprus","Cyprus" },
                                     { Guid.NewGuid(), "Czechia (Czech Republic)","Czechi" },
                                     { Guid.NewGuid(), "Democratic Republic of the Congo","Democr" },
                                     { Guid.NewGuid(), "Denmark","Denmar" },
                                     { Guid.NewGuid(), "Djibouti","Djibou" },
                                     { Guid.NewGuid(), "Dominica","Domini" },
                                     { Guid.NewGuid(), "Dominican Republic","Domini" },
                                     { Guid.NewGuid(), "Ecuador","Ecuado" },
                                     { Guid.NewGuid(), "Egypt","Egypt" },
                                     { Guid.NewGuid(), "El Salvador","El Sal" },
                                     { Guid.NewGuid(), "Equatorial Guinea","Equato" },
                                     { Guid.NewGuid(), "Eritrea","Eritre" },
                                     { Guid.NewGuid(), "Estonia","Estoni" },
                                     { Guid.NewGuid(), "Eswatini (fmr. Swaziland)","Eswati" },
                                     { Guid.NewGuid(), "Ethiopia","Ethiop" },
                                     { Guid.NewGuid(), "Fiji","Fiji" },
                                     { Guid.NewGuid(), "Finland","Finlan" },
                                     { Guid.NewGuid(), "France","France" },
                                     { Guid.NewGuid(), "Gabon","Gabon" },
                                     { Guid.NewGuid(), "Gambia","Gambia" },
                                     { Guid.NewGuid(), "Georgia","Georgi" },
                                     { Guid.NewGuid(), "Germany","German" },
                                     { Guid.NewGuid(), "Ghana","Ghana" },
                                     { Guid.NewGuid(), "Greece","Greece" },
                                     { Guid.NewGuid(), "Grenada","Grenad" },
                                     { Guid.NewGuid(), "Guatemala","Guatem" },
                                     { Guid.NewGuid(), "Guinea","Guinea" },
                                     { Guid.NewGuid(), "Guinea-Bissau","Guinea" },
                                     { Guid.NewGuid(), "Guyana","Guyana" },
                                     { Guid.NewGuid(), "Haiti","Haiti" },
                                     { Guid.NewGuid(), "Holy See","Holy S" },
                                     { Guid.NewGuid(), "Honduras","Hondur" },
                                     { Guid.NewGuid(), "Hungary","Hungar" },
                                     { Guid.NewGuid(), "Iceland","Icelan" },
                                     { Guid.NewGuid(), "India","India" },
                                     { Guid.NewGuid(), "Indonesia","Indone" },
                                     { Guid.NewGuid(), "Iran","Iran" },
                                     { Guid.NewGuid(), "Iraq","Iraq" },
                                     { Guid.NewGuid(), "Ireland","Irelan" },
                                     { Guid.NewGuid(), "Israel","Israel" },
                                     { Guid.NewGuid(), "Italy","Italy" },
                                     { Guid.NewGuid(), "Jamaica","Jamaic" },
                                     { Guid.NewGuid(), "Japan","Japan" },
                                     { Guid.NewGuid(), "Jordan","Jordan" },
                                     { Guid.NewGuid(), "Kazakhstan","Kazakh" },
                                     { Guid.NewGuid(), "Kenya","Kenya" },
                                     { Guid.NewGuid(), "Kiribati","Kiriba" },
                                     { Guid.NewGuid(), "Kuwait","Kuwait" },
                                     { Guid.NewGuid(), "Kyrgyzstan","Kyrgyz" },
                                     { Guid.NewGuid(), "Laos","Laos" },
                                     { Guid.NewGuid(), "Latvia","Latvia" },
                                     { Guid.NewGuid(), "Lebanon","Lebano" },
                                     { Guid.NewGuid(), "Lesotho","Lesoth" },
                                     { Guid.NewGuid(), "Liberia","Liberi" },
                                     { Guid.NewGuid(), "Libya","Libya" },
                                     { Guid.NewGuid(), "Liechtenstein","Liecht" },
                                     { Guid.NewGuid(), "Lithuania","Lithua" },
                                     { Guid.NewGuid(), "Luxembourg","Luxemb" },
                                     { Guid.NewGuid(), "Madagascar","Madaga" },
                                     { Guid.NewGuid(), "Malawi","Malawi" },
                                     { Guid.NewGuid(), "Malaysia","Malays" },
                                     { Guid.NewGuid(), "Maldives","Maldiv" },
                                     { Guid.NewGuid(), "Mali","Mali" },
                                     { Guid.NewGuid(), "Malta","Malta" },
                                     { Guid.NewGuid(), "Marshall Islands","Marsha" },
                                     { Guid.NewGuid(), "Mauritania","Maurit" },
                                     { Guid.NewGuid(), "Mauritius","Maurit" },
                                     { Guid.NewGuid(), "Mexico","Mexico" },
                                     { Guid.NewGuid(), "Micronesia","Micron" },
                                     { Guid.NewGuid(), "Moldova","Moldov" },
                                     { Guid.NewGuid(), "Monaco","Monaco" },
                                     { Guid.NewGuid(), "Mongolia","Mongol" },
                                     { Guid.NewGuid(), "Montenegro","Monten" },
                                     { Guid.NewGuid(), "Morocco","Morocc" },
                                     { Guid.NewGuid(), "Mozambique","Mozamb" },
                                     { Guid.NewGuid(), "Myanmar (formerly Burma)","Myanma" },
                                     { Guid.NewGuid(), "Namibia","Namibi" },
                                     { Guid.NewGuid(), "Nauru","Nauru" },
                                     { Guid.NewGuid(), "Nepal","Nepal" },
                                     { Guid.NewGuid(), "Netherlands","Nether" },
                                     { Guid.NewGuid(), "New Zealand","New Ze" },
                                     { Guid.NewGuid(), "Nicaragua","Nicara" },
                                     { Guid.NewGuid(), "Niger","Niger" },
                                     { Guid.NewGuid(), "Nigeria","Nigeri" },
                                     { Guid.NewGuid(), "North Korea","North " },
                                     { Guid.NewGuid(), "North Macedonia","North " },
                                     { Guid.NewGuid(), "Norway","Norway" },
                                     { Guid.NewGuid(), "Oman","Oman" },
                                     { Guid.NewGuid(), "Pakistan","Pakist" },
                                     { Guid.NewGuid(), "Palau","Palau" },
                                     { Guid.NewGuid(), "Palestine State","Palest" },
                                     { Guid.NewGuid(), "Panama","Panama" },
                                     { Guid.NewGuid(), "Papua New Guinea","Papua " },
                                     { Guid.NewGuid(), "Paraguay","Paragu" },
                                     { Guid.NewGuid(), "Peru","Peru" },
                                     { Guid.NewGuid(), "Philippines","Philip" },
                                     { Guid.NewGuid(), "Poland","Poland" },
                                     { Guid.NewGuid(), "Portugal","Portug" },
                                     { Guid.NewGuid(), "Qatar","Qatar" },
                                     { Guid.NewGuid(), "Romania","Romani" },
                                     { Guid.NewGuid(), "Russia","Russia" },
                                     { Guid.NewGuid(), "Rwanda","Rwanda" },
                                     { Guid.NewGuid(), "Saint Kitts and Nevis","Saint " },
                                     { Guid.NewGuid(), "Saint Lucia","Saint " },
                                     { Guid.NewGuid(), "Saint Vincent and the Grenadines","Saint " },
                                     { Guid.NewGuid(), "Samoa","Samoa" },
                                     { Guid.NewGuid(), "San Marino","San Ma" },
                                     { Guid.NewGuid(), "Sao Tome and Principe","Sao To" },
                                     { Guid.NewGuid(), "Saudi Arabia","Saudi " },
                                     { Guid.NewGuid(), "Senegal","Senega" },
                                     { Guid.NewGuid(), "Serbia","Serbia" },
                                     { Guid.NewGuid(), "Seychelles","Seyche" },
                                     { Guid.NewGuid(), "Sierra Leone","Sierra" },
                                     { Guid.NewGuid(), "Singapore","Singap" },
                                     { Guid.NewGuid(), "Slovakia","Slovak" },
                                     { Guid.NewGuid(), "Slovenia","Sloven" },
                                     { Guid.NewGuid(), "Solomon Islands","Solomo" },
                                     { Guid.NewGuid(), "Somalia","Somali" },
                                     { Guid.NewGuid(), "South Africa","South " },
                                     { Guid.NewGuid(), "South Korea","South " },
                                     { Guid.NewGuid(), "South Sudan","South " },
                                     { Guid.NewGuid(), "Spain","Spain" },
                                     { Guid.NewGuid(), "Sri Lanka","Sri La" },
                                     { Guid.NewGuid(), "Sudan","Sudan" },
                                     { Guid.NewGuid(), "Suriname","Surina" },
                                     { Guid.NewGuid(), "Sweden","Sweden" },
                                     { Guid.NewGuid(), "Switzerland","Switze" },
                                     { Guid.NewGuid(), "Syria","Syria" },
                                     { Guid.NewGuid(), "Tajikistan","Tajiki" },
                                     { Guid.NewGuid(), "Tanzania","Tanzan" },
                                     { Guid.NewGuid(), "Thailand","Thaila" },
                                     { Guid.NewGuid(), "Timor-Leste","Timor-" },
                                     { Guid.NewGuid(), "Togo","Togo" },
                                     { Guid.NewGuid(), "Tonga","Tonga" },
                                     { Guid.NewGuid(), "Trinidad and Tobago","Trinid" },
                                     { Guid.NewGuid(), "Tunisia","Tunisi" },
                                     { Guid.NewGuid(), "Turkey","Turkey" },
                                     { Guid.NewGuid(), "Turkmenistan","Turkme" },
                                     { Guid.NewGuid(), "Tuvalu","Tuvalu" },
                                     { Guid.NewGuid(), "Uganda","Uganda" },
                                     { Guid.NewGuid(), "Ukraine","Ukrain" },
                                     { Guid.NewGuid(), "United Arab Emirates","United" },
                                     { Guid.NewGuid(), "United Kingdom","United" },
                                     { Guid.NewGuid(), "United States of America","United" },
                                     { Guid.NewGuid(), "Uruguay","Urugua" },
                                     { Guid.NewGuid(), "Uzbekistan","Uzbeki" },
                                     { Guid.NewGuid(), "Vanuatu","Vanuat" },
                                     { Guid.NewGuid(), "Venezuela","Venezu" },
                                     { Guid.NewGuid(), "Vietnam","Vietna" },
                                     { Guid.NewGuid(), "Yemen","Yemen" },
                                     { Guid.NewGuid(), "Zambia","Zambia" },
                                     { Guid.NewGuid(), "Zimbabwe","Zimbab" }
                                 });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Abbreviation",
                table: "BirthPlaces");
        }
    }
}
