using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ForSureLife.repo.Migrations
{
    public partial class AddingBirthPlaces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BirthPlaces",
                columns: table => new
                {
                    BirthPlacesId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BirthPlaces", x => x.BirthPlacesId);
                });




        migrationBuilder.InsertData(
                        table: "BirthPlaces",
                        columns: new[] { "BirthPlacesId", "Name" },
                        values: new object[,]
                        {
                         {Guid.NewGuid(), "Alabama" },
                         {Guid.NewGuid(), "Alaska" },
                         {Guid.NewGuid(), "Arizona" },
                         {Guid.NewGuid(), "Arkansas" },
                         {Guid.NewGuid(), "California" },
                         {Guid.NewGuid(), "Colorado" },
                         {Guid.NewGuid(), "Connecticut" },
                         {Guid.NewGuid(), "Delaware" },
                         {Guid.NewGuid(), "Florida" },
                         {Guid.NewGuid(), "Georgia" },
                         {Guid.NewGuid(), "Hawaii" },
                         {Guid.NewGuid(), "Idaho" },
                         {Guid.NewGuid(), "Illinois" },
                         {Guid.NewGuid(), "Indiana" },
                         {Guid.NewGuid(), "Iowa" },
                         {Guid.NewGuid(), "Kansas" },
                         {Guid.NewGuid(), "Kentucky" },
                         {Guid.NewGuid(), "Louisiana" },
                         {Guid.NewGuid(), "Maine" },
                         {Guid.NewGuid(), "Maryland" },
                         {Guid.NewGuid(), "Massachusetts" },
                         {Guid.NewGuid(), "Michigan" },
                         {Guid.NewGuid(), "Minnesota" },
                         {Guid.NewGuid(), "Mississippi" },
                         {Guid.NewGuid(), "Missouri" },
                         {Guid.NewGuid(), "Montana" },
                         {Guid.NewGuid(), "Nebraska" },
                         {Guid.NewGuid(), "Nevada" },
                         {Guid.NewGuid(), "New Hampshire" },
                         {Guid.NewGuid(), "New Jersey" },
                         {Guid.NewGuid(), "New Mexico" },
                         {Guid.NewGuid(), "New York" },
                         {Guid.NewGuid(), "North Carolina" },
                         {Guid.NewGuid(), "North Dakota" },
                         {Guid.NewGuid(), "Ohio" },
                         {Guid.NewGuid(), "Oklahoma" },
                         {Guid.NewGuid(), "Oregon" },
                         {Guid.NewGuid(), "Pennsylvania" },
                         {Guid.NewGuid(), "Rhode Island" },
                         {Guid.NewGuid(), "South Carolina" },
                         {Guid.NewGuid(), "South Dakota" },
                         {Guid.NewGuid(), "Tennessee" },
                         {Guid.NewGuid(), "Texas" },
                         {Guid.NewGuid(), "Utah" },
                         {Guid.NewGuid(), "Vermont" },
                         {Guid.NewGuid(), "Virginia" },
                         {Guid.NewGuid(), "Washington" },
                         {Guid.NewGuid(), "West Virginia" },
                         {Guid.NewGuid(), "Wisconsin" },
                         {Guid.NewGuid(), "Wyoming" },
                         {Guid.NewGuid(), "American Samoa" },
                         {Guid.NewGuid(), "District of Columbia" },
                         {Guid.NewGuid(), "Federated States of Micronesia" },
                         {Guid.NewGuid(), "Guam" },
                         {Guid.NewGuid(), "Marshall Islands" },
                         {Guid.NewGuid(), "Northern Mariana Islands" },
                         {Guid.NewGuid(), "Palau" },
                         {Guid.NewGuid(), "Puerto Rico" },
                         {Guid.NewGuid(), "Virgin Islands" },
                         {Guid.NewGuid(), "Armed Forces Africa" },
                         {Guid.NewGuid(), "Armed Forces Americas" },
                         {Guid.NewGuid(), "Armed Forces Canada" },
                         {Guid.NewGuid(), "Armed Forces Europe" },
                         {Guid.NewGuid(), "Armed Forces Middle East" },
                         {Guid.NewGuid(), "Armed Forces Pacific" },
                         {Guid.NewGuid(), "Afghanistan" },
                         {Guid.NewGuid(), "Albania" },
                         {Guid.NewGuid(), "Algeria" },
                         {Guid.NewGuid(), "Andorra" },
                         {Guid.NewGuid(), "Angola" },
                         {Guid.NewGuid(), "Antigua and Barbuda" },
                         {Guid.NewGuid(), "Argentina" },
                         {Guid.NewGuid(), "Armenia" },
                         {Guid.NewGuid(), "Australia" },
                         {Guid.NewGuid(), "Austria" },
                         {Guid.NewGuid(), "Azerbaijan" },
                         {Guid.NewGuid(), "Bahamas" },
                         {Guid.NewGuid(), "Bahrain" },
                         {Guid.NewGuid(), "Bangladesh" },
                         {Guid.NewGuid(), "Barbados" },
                         {Guid.NewGuid(), "Belarus" },
                         {Guid.NewGuid(), "Belgium" },
                         {Guid.NewGuid(), "Belize" },
                         {Guid.NewGuid(), "Benin" },
                         {Guid.NewGuid(), "Bhutan" },
                         {Guid.NewGuid(), "Bolivia" },
                         {Guid.NewGuid(), "Bosnia and Herzegovina" },
                         {Guid.NewGuid(), "Botswana" },
                         {Guid.NewGuid(), "Brazil" },
                         {Guid.NewGuid(), "Brunei" },
                         {Guid.NewGuid(), "Bulgaria" },
                         {Guid.NewGuid(), "Burkina Faso" },
                         {Guid.NewGuid(), "Burundi" },
                         {Guid.NewGuid(), "Côte d'Ivoire" },
                         {Guid.NewGuid(), "Cabo Verde" },
                         {Guid.NewGuid(), "Cambodia" },
                         {Guid.NewGuid(), "Cameroon" },
                         {Guid.NewGuid(), "Canada" },
                         {Guid.NewGuid(), "Central African Republic" },
                         {Guid.NewGuid(), "Chad" },
                         {Guid.NewGuid(), "Chile" },
                         {Guid.NewGuid(), "China" },
                         {Guid.NewGuid(), "Colombia" },
                         {Guid.NewGuid(), "Comoros" },
                         {Guid.NewGuid(), "Congo (Congo-Brazzaville)" },
                         {Guid.NewGuid(), "Costa Rica" },
                         {Guid.NewGuid(), "Croatia" },
                         {Guid.NewGuid(), "Cuba" },
                         {Guid.NewGuid(), "Cyprus" },
                         {Guid.NewGuid(), "Czechia (Czech Republic)" },
                         {Guid.NewGuid(), "Democratic Republic of the Congo" },
                         {Guid.NewGuid(), "Denmark" },
                         {Guid.NewGuid(), "Djibouti" },
                         {Guid.NewGuid(), "Dominica" },
                         {Guid.NewGuid(), "Dominican Republic" },
                         {Guid.NewGuid(), "Ecuador" },
                         {Guid.NewGuid(), "Egypt" },
                         {Guid.NewGuid(), "El Salvador" },
                         {Guid.NewGuid(), "Equatorial Guinea" },
                         {Guid.NewGuid(), "Eritrea" },
                         {Guid.NewGuid(), "Estonia" },
                         {Guid.NewGuid(), "Eswatini (fmr. Swaziland)" },
                         {Guid.NewGuid(), "Ethiopia" },
                         {Guid.NewGuid(), "Fiji" },
                         {Guid.NewGuid(), "Finland" },
                         {Guid.NewGuid(), "France" },
                         {Guid.NewGuid(), "Gabon" },
                         {Guid.NewGuid(), "Gambia" },
                         {Guid.NewGuid(), "Georgia" },
                         {Guid.NewGuid(), "Germany" },
                         {Guid.NewGuid(), "Ghana" },
                         {Guid.NewGuid(), "Greece" },
                         {Guid.NewGuid(), "Grenada" },
                         {Guid.NewGuid(), "Guatemala" },
                         {Guid.NewGuid(), "Guinea" },
                         {Guid.NewGuid(), "Guinea-Bissau" },
                         {Guid.NewGuid(), "Guyana" },
                         {Guid.NewGuid(), "Haiti" },
                         {Guid.NewGuid(), "Holy See" },
                         {Guid.NewGuid(), "Honduras" },
                         {Guid.NewGuid(), "Hungary" },
                         {Guid.NewGuid(), "Iceland" },
                         {Guid.NewGuid(), "India" },
                         {Guid.NewGuid(), "Indonesia" },
                         {Guid.NewGuid(), "Iran" },
                         {Guid.NewGuid(), "Iraq" },
                         {Guid.NewGuid(), "Ireland" },
                         {Guid.NewGuid(), "Israel" },
                         {Guid.NewGuid(), "Italy" },
                         {Guid.NewGuid(), "Jamaica" },
                         {Guid.NewGuid(), "Japan" },
                         {Guid.NewGuid(), "Jordan" },
                         {Guid.NewGuid(), "Kazakhstan" },
                         {Guid.NewGuid(), "Kenya" },
                         {Guid.NewGuid(), "Kiribati" },
                         {Guid.NewGuid(), "Kuwait" },
                         {Guid.NewGuid(), "Kyrgyzstan" },
                         {Guid.NewGuid(), "Laos" },
                         {Guid.NewGuid(), "Latvia" },
                         {Guid.NewGuid(), "Lebanon" },
                         {Guid.NewGuid(), "Lesotho" },
                         {Guid.NewGuid(), "Liberia" },
                         {Guid.NewGuid(), "Libya" },
                         {Guid.NewGuid(), "Liechtenstein" },
                         {Guid.NewGuid(), "Lithuania" },
                         {Guid.NewGuid(), "Luxembourg" },
                         {Guid.NewGuid(), "Madagascar" },
                         {Guid.NewGuid(), "Malawi" },
                         {Guid.NewGuid(), "Malaysia" },
                         {Guid.NewGuid(), "Maldives" },
                         {Guid.NewGuid(), "Mali" },
                         {Guid.NewGuid(), "Malta" },
                         {Guid.NewGuid(), "Marshall Islands" },
                         {Guid.NewGuid(), "Mauritania" },
                         {Guid.NewGuid(), "Mauritius" },
                         {Guid.NewGuid(), "Mexico" },
                         {Guid.NewGuid(), "Micronesia" },
                         {Guid.NewGuid(), "Moldova" },
                         {Guid.NewGuid(), "Monaco" },
                         {Guid.NewGuid(), "Mongolia" },
                         {Guid.NewGuid(), "Montenegro" },
                         {Guid.NewGuid(), "Morocco" },
                         {Guid.NewGuid(), "Mozambique" },
                         {Guid.NewGuid(), "Myanmar (formerly Burma)" },
                         {Guid.NewGuid(), "Namibia" },
                         {Guid.NewGuid(), "Nauru" },
                         {Guid.NewGuid(), "Nepal" },
                         {Guid.NewGuid(), "Netherlands" },
                         {Guid.NewGuid(), "New Zealand" },
                         {Guid.NewGuid(), "Nicaragua" },
                         {Guid.NewGuid(), "Niger" },
                         {Guid.NewGuid(), "Nigeria" },
                         {Guid.NewGuid(), "North Korea" },
                         {Guid.NewGuid(), "North Macedonia" },
                         {Guid.NewGuid(), "Norway" },
                         {Guid.NewGuid(), "Oman" },
                         {Guid.NewGuid(), "Pakistan" },
                         {Guid.NewGuid(), "Palau" },
                         {Guid.NewGuid(), "Palestine State" },
                         {Guid.NewGuid(), "Panama" },
                         {Guid.NewGuid(), "Papua New Guinea" },
                         {Guid.NewGuid(), "Paraguay" },
                         {Guid.NewGuid(), "Peru" },
                         {Guid.NewGuid(), "Philippines" },
                         {Guid.NewGuid(), "Poland" },
                         {Guid.NewGuid(), "Portugal" },
                         {Guid.NewGuid(), "Qatar" },
                         {Guid.NewGuid(), "Romania" },
                         {Guid.NewGuid(), "Russia" },
                         {Guid.NewGuid(), "Rwanda" },
                         {Guid.NewGuid(), "Saint Kitts and Nevis" },
                         {Guid.NewGuid(), "Saint Lucia" },
                         {Guid.NewGuid(), "Saint Vincent and the Grenadines" },
                         {Guid.NewGuid(), "Samoa" },
                         {Guid.NewGuid(), "San Marino" },
                         {Guid.NewGuid(), "Sao Tome and Principe" },
                         {Guid.NewGuid(), "Saudi Arabia" },
                         {Guid.NewGuid(), "Senegal" },
                         {Guid.NewGuid(), "Serbia" },
                         {Guid.NewGuid(), "Seychelles" },
                         {Guid.NewGuid(), "Sierra Leone" },
                         {Guid.NewGuid(), "Singapore" },
                         {Guid.NewGuid(), "Slovakia" },
                         {Guid.NewGuid(), "Slovenia" },
                         {Guid.NewGuid(), "Solomon Islands" },
                         {Guid.NewGuid(), "Somalia" },
                         {Guid.NewGuid(), "South Africa" },
                         {Guid.NewGuid(), "South Korea" },
                         {Guid.NewGuid(), "South Sudan" },
                         {Guid.NewGuid(), "Spain" },
                         {Guid.NewGuid(), "Sri Lanka" },
                         {Guid.NewGuid(), "Sudan" },
                         {Guid.NewGuid(), "Suriname" },
                         {Guid.NewGuid(), "Sweden" },
                         {Guid.NewGuid(), "Switzerland" },
                         {Guid.NewGuid(), "Syria" },
                         {Guid.NewGuid(), "Tajikistan" },
                         {Guid.NewGuid(), "Tanzania" },
                         {Guid.NewGuid(), "Thailand" },
                         {Guid.NewGuid(), "Timor-Leste" },
                         {Guid.NewGuid(), "Togo" },
                         {Guid.NewGuid(), "Tonga" },
                         {Guid.NewGuid(), "Trinidad and Tobago" },
                         {Guid.NewGuid(), "Tunisia" },
                         {Guid.NewGuid(), "Turkey" },
                         {Guid.NewGuid(), "Turkmenistan" },
                         {Guid.NewGuid(), "Tuvalu" },
                         {Guid.NewGuid(), "Uganda" },
                         {Guid.NewGuid(), "Ukraine" },
                         {Guid.NewGuid(), "United Arab Emirates" },
                         {Guid.NewGuid(), "United Kingdom" },
                         {Guid.NewGuid(), "United States of America" },
                         {Guid.NewGuid(), "Uruguay" },
                         {Guid.NewGuid(), "Uzbekistan" },
                         {Guid.NewGuid(), "Vanuatu" },
                         {Guid.NewGuid(), "Venezuela" },
                         {Guid.NewGuid(), "Vietnam" },
                         {Guid.NewGuid(), "Yemen" },
                         {Guid.NewGuid(), "Zambia" },
                         {Guid.NewGuid(), "Zimbabwe" }

                        });

         }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BirthPlaces");
        }
    }
}
